runtime: python311
entrypoint: gunicorn --bind=0.0.0.0:8000 --workers=2 --threads=4 --timeout=60 --chdir=/workspace/testProject testProject.wsgi:application

handlers:
  - url: /.*
    script: auto

env_variables:
  PORT: 8000
