steps:
  - name: 'gcr.io/cloud-builders/gcloud:latest'
    args: ['app', 'deploy', '--ignore-errors']
  - name: 'gcr.io/cloud-builders/gcloud:latest'
    args: ['app', 'services', 'set-traffic', '--migrate']