steps:
  - name: 'gcr.io/cloud-builders/gcloud:latest'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud app deploy --quiet --project $PROJECT_ID --version $SHORT_SHA || true
  - name: 'gcr.io/cloud-builders/gcloud:latest'
    args: ['app', 'services', 'set-traffic', '--splits', '89a4a9b=1', '--migrate']